### ISSUE TITLE
Create docker environment to run application

### ISSUE THREAD

**Issue by ewold** [Pokebag/pokebag-devops#2]
Docker would gives us an application in a container that is faster to setup and scale if it would be needed. 

Install docker 1.10 or 1.12

**Comment by ewold** [comment]
Docker 1.12 Installed

**Comment by trezy** [comment]
@ewold, where is Docker installed? Just on the server? It'd be great if we had the configuration necessary in each repo to start the system with `docker-compose` so that we can better mimic our production environment. :-)

**Comment by ewold** [comment]
Just on the server, still have to look at the app side to see if we can put it into a docker image.
